version: "3.7"

services:
  api:
    build: .
    container_name: RegisterCenterNode1
    ports:
      - "8761:8761"
    networks:
      - artist-saas-net

networks:
  artist-saas-net:
    driver: bridge
    name: artist-saas-net